### ISSUE TITLE
ACR122 reader support

### ISSUE THREAD

**Issue by mogar** [AdamLaurie/RFIDIOt#30]
It looks like the ACR122 reader isn't supported for pn532emulate.py. It's not in the officially supported readers list, and if I try anyway I get the following error:

```
Traceback (most recent call last):
  File "pn532emulate.py", line 135, in <module>
    status= card.acs_send_apdu(PN532_APDU['TG_INIT_AS_TARGET']+mode+sens_res+uid+sel_res+felica+nfcid+lengt+gt+lentk+tk)
  File "/home/nvidia/Documents/RFIDIOt/rfidiot/RFIDIOt.py", line 1186, in acs_send_apdu
    result, sw1, sw2= self.acs_transmit_apdu(apduout)
  File "/home/nvidia/Documents/RFIDIOt/rfidiot/RFIDIOt.py", line 1231, in acs_transmit_apdu
    sw1 = response[-2]
IndexError: list index out of range
```

What would it take to get pn532emulate.py working with this reader?

**Comment by hopkinskong** [comment]
Are you using `ACR1212U215`?

**Comment by MAVProxyUser** [comment]
Emulation does not work for me on ACR122U215 either.
