### ISSUE TITLE
Problems with emulate ACR122

### ISSUE THREAD

**Issue by alhkytran** [AdamLaurie/RFIDIOt#49]
I tried to use pn532mitm.py with 2 acr122 to read and emulated.
The part to read no have problem, wait for a card and when the card is closed read and wait for emulated, in this step get trouble in

`emulator.acs_send_apdu(PN532_APDU['TG_INIT_AS_TARGET']+mode+sens_res+uid+sel_res+felica+nfcid+lengt+gt+lentk+tk`

The error is:
```
Traceback (most recent call last):
  File "pn532mitm.py", line 315, in <module>
    status= emulator.acs_send_apdu(PN532_APDU['TG_INIT_AS_TARGET']+mode+sens_res+uid+sel_res+felica+nfcid+lengt+gt+lentk+tk)
  File "$HOME/RFIDIOt/rfidiot/RFIDIOt.py", line 1212, in acs_send_apdu
    result, sw1, sw2= self.acs_transmit_apdu(apduout)
  File "$HOME/RFIDIOt/rfidiot/RFIDIOt.py", line 1258, in acs_transmit_apdu
    sw1 = response[-2]
IndexError: list index out of range

```
The readers information is:
```
Reader NXP PN532 Firmware:
       IC: 32
      Rev: 1.6
```

And the command that used was
`python pn532mitm.py -r 0 1`

Can someone help me with this problem??

**Comment by AlfonsoLopezContreras** [comment]
I have the same issue, anyone found a solution?
